MODEL_NAME = '4bit/llava-v1.5-7b-5GB'
GPT_JSON = {"max_tokens": 4096, "model_name": "gpt-3.5-turbo",
            "openai_api_key": "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", "temperature": 0.8}

DEFAULT_COLUMNS_QUANTITY = 5
DEFAULT_IMAGE_QUANTITY_DELIMETER = 5
DEFAULT_IMAGE_VALIDATION = DEFAULT_IMAGE_QUANTITY_DELIMETER * 2

NUM_SECONDS_TO_SLEEP = 3
